# ===== SHARD 0 (MySQL instance 1) =====
shard.0.url=jdbc:mysql://localhost:3306/urldb_shard0
shard.0.username=root
shard.0.password=yourpassword

# ===== SHARD 1 (MySQL instance 2) =====
shard.1.url=jdbc:mysql://localhost:3307/urldb_shard1
shard.1.username=root
shard.1.password=yourpassword

# ===== REDIS =====
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===== SERVER =====
server.port=8080

# ===== DISABLES THE SPRING AUTO DATASOURCE =====
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration